export const COLLAPSE_MENU = 'COLLAPSE_MENU';
export const COLLAPSE_TOGGLE = 'COLLAPSE_TOGGLE';
export const FULL_SCREEN = 'FULL_SCREEN';
export const FULL_SCREEN_EXIT = 'FULL_SCREEN_EXIT';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const NAV_CONTENT_LEAVE = 'NAV_CONTENT_LEAVE';
export const NAV_COLLAPSE_LEAVE = 'NAV_COLLAPSE_LEAVE';

//transactions actions
export const GET_TRANSACTIONS = "GET_TRANSACTIONS"
export const DELETE_TRANSACTION = "DELETE_TRANSACTION"
export const ADD_TRANSACTION = "ADD_TRANSACTION"
export const TRANSACTION_ERROR = "TRANSACTION_ERROR"